Rails/config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'users/create'

  get 'users/me'

  get 'home/index'

  get 'sessions/create'

  get 'sessions/destroy'

  root 'home#index' #ヘッダリンク用 http://localhost:3000/
  resources :boards, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :comments, only: %i[create destroy edit update]
end

Rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Rails/app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :integer          not null, primary key
#  body       :text(65535)
#  good       :integer          default(0), not null
#  name       :string(255)
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Board < ApplicationRecord
  has_many :comments, dependent: :delete_all
  has_many :board_tag_relations, dependent: :delete_all
  has_many :tags, through: :board_tag_relations

  validates :name, presence: true, length: {maximum: 10 }
  validates :title, presence: true, length: {maximum: 30 }
  validates :body, presence: true, length: {maximum: 100 }
end

Rails/app/models/board_tag_relation.rb
# == Schema Information
#
# Table name: board_tag_relations
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :integer
#  tag_id     :integer
#
# Foreign Keys
#
#  fk_rails_...  (board_id => boards.id)
#  fk_rails_...  (tag_id => tags.id)
#
class BoardTagRelation < ApplicationRecord
  belongs_to :board
  belongs_to :tag
end

Rails/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  comment    :text(65535)      not null
#  name       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :integer
#
# Foreign Keys
#
#  fk_rails_...  (board_id => boards.id)
#
class Comment < ApplicationRecord
  belongs_to :board

  validates :name, presence: true, length: {maximum: 10 }
  validates :comment, presence: true, length: {maximum: 100}
end

Rails/app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Tag < ApplicationRecord
  has_many :board_tag_relations, dependent: :delete_all
  has_many :boards, through: :board_tag_relations
end

Rails/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)      not null
#  password_digest :string(255)      not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
end

Rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Rails/app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_target_board, only: %i[show edit update destroy]

  def index
    # binding.pry
    # デフォルト25件
    # @boards = Board.page(params[:page]).per(20)

    @boards = params[:tag_id].present? ? Tag.find(params[:tag_id]).boards : Board.all
    @boards = @boards.page(params[:page])

  end
  
  
  def new
    # @board = Board.new
    @board = Board.new(flash[:board])
  end

  def create
    # board = Board.create(board_params)
    board = Board.new(board_params)
    if board.save # saveできた時の処理
      flash[:notice] = "「#{board.title}」の掲示板を作成しました"
      # binding.pry
      # 作ったボードidのページにリダイレクト
      redirect_to board
    else
      redirect_to new_board_path, flash: {
        board: board,
        error_messages: board.errors.full_messages
      }
    end
  end

  def show
    ## -- boardについての記載ないが、RailsがURLに沿った形を吐き出してくれているのかも。 -- ##
    # 掲示板に紐づいたcommentモデルを作成
    # @comment = @board.comments.new
    # 上の書き方だと、常にnewで作られた空のコメントが一覧に含まれることになる
    @comment = Comment.new(board_id: @board.id)

    # いいねボタン
    @board = Board.find(params[:id])
    # good = @board.good;
    # good = @board.good * 3
    # @board.good = good
    @board.good += 1
    # ↓を書くとshowにリダイレクト->showが表示されてもう一回リダイレクトの流れになる
    # redirect_to @board
  end

  def edit
  end

  def update
    # board = Board.find(params[:id])

    # モデルオブジェクトの、updateメソッドを使用する
    # board.update(board_params)
    # set_target_boardを使った時は、board = とboardに値が入っているわけではないのでインスタンスを@で直指定する
    # @board.update(board_params)
    

    #リダイレクト処理 /boards/:idのパスにリダイレクトされる
    # redirect_to board
    # redirect_to @board

    is_update = @board.update(board_params)
    if is_update == true
      redirect_to @board
    else
      redirect_to :back, flash: {
        board: @board,
        error_messages: @board.errors.full_messages
      }
    end

  end

  def destroy
    # board = Board.find(params[:id])
    # @board.delete
    @board.destroy

    redirect_to boards_path, flash: { notice: "「#{@board.title}」の掲示板が削除されました"}
  end

  private

  def board_params
    params.require(:board).permit(:name, :title, :body, :good, tag_ids: [])
  end

  def set_target_board
    @board = Board.find(params[:id])
  end

end

Rails/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)
    if comment.save
      flash[:notice] = 'コメントを投稿しました'
      redirect_to comment.board
    else
      redirect_to :back, flash: {
        comment: comment,
        error_messages: comment.errors.full_messages
      }
    end

  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    is_update = @comment.update(comment_params)
    session[:test_session] = 'セッションデータです'
    cookies[:test_cookie] = 'クッキーだよ'
    if is_update == true
      @board = Board.find(@comment.board_id)
      session[:test_session] = nil # session削除
      cookies.delete :test_cookie # cookieの削除
      redirect_to @board
    else
      redirect_to :back, flash: {
        comment: @comment,
        error_messages: @comment.errors.full_messages,
        flash_name: 'flash_nameです',
        flash_param: params
      }
    end
  end

  def destroy
    # board = Board.find(params[:id])
    comment = Comment.find(params[:id])
    comment.delete
    # 紐づいていた掲示板画面に遷移させる
    redirect_to comment.board, flash: { notice: 'コメントが削除されました' }
  end

  private

  def comment_params
    params.require(:comment).permit(:board_id, :name, :comment)
  end
end

Rails/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

Rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  end

  def destroy
  end
end

Rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
  end

  def me
  end
end

Rails/app/helpers/application_helper.rb
module ApplicationHelper
  # リンクの表示名とパスを受け取る
  def header_link_item(name, path)
    class_name = 'nav-item'
    # もし表示するページのパスと、引数のパスが同じだったらclass_にactiveを追加
    class_name << 'active' if current_page?(path)

    # 任意のhtmliタグを作るヘルパ <li><a></a></li>という形でできる
    content_tag :li, class: class_name do
      link_to name, path, class: 'nav-link'
    end

  end
end

Rails/app/helpers/comments_helper.rb
module CommentsHelper
end

Rails/app/helpers/home_helper.rb
module HomeHelper
end

Rails/app/helpers/sessions_helper.rb
module SessionsHelper
end

Rails/app/helpers/users_helper.rb
module UsersHelper
end

Rails/app/views/application/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">BoardApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= header_link_item('Home', root_path) %>
      <%= header_link_item('Boards', boards_path) %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

Rails/app/views/boards/_board.html.erb
<div class="card">
  <div class="card-header">
    <h4><%= board.title %></h4>
    <% board.tags.each do |tag| %>
      <span class="badge badge-primary"><%= tag.name %></span>
    <% end %>
  </div>
  <div class="card-body">
    <p class="card-text">
      <%= simple_format(board.body) %>
    </p>
    <p class="text-right font-weight-bold mr-10"><%= board.name %></p>
    <div class="text-right">

      <%# いいねぼたん %>
      <%= form_for @board do |f|%>
        <%= f.hidden_field :good, value: board.good %>
        <%= f.submit '💕 x ' << board.good.to_s , class: 'btn btn-success btn-sm' %>
        <%# 下と上は同じ %>
        <button class="btn btn-sm">💕 x <%= board.good %> </button>
      <% end %>


    </div>
  </div>
</div>

Rails/app/views/boards/_form.html.erb
<%= render 'shared/error_messages' %>

<%= form_for board do |f| %>
  <div class="form-group">
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :title, 'タイトル' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :body, '本文' %>
    <%= f.text_area :body, class: 'form-control', rows: 10 %>
  </div>

  <div class="form-group">
    <span>タグ</span>
    <%#
      tagが存在する分だけチェックボックスを作るメソッドのcollenction_check_boxes
     boardオブジェクトのプロパティ名tag_ids 多対多の設定によりこれが追加されている。 
     タグIDのリストを渡すことで複数のタグを紐づけられる
     多対多のものを紐づける場合は、:モデル名_idsで紐づけることができる

     Tag.all : タグオブジェクトのリスト
     :id, :name : ここのtagオブジェクトのid, nameプロパティを記述
     
      %>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class="form-check">
        <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%= tag.text %>
        <% end %>
      </div>
    <% end %>
  </div>

  <%= f.submit '保存', class: 'btn btn-primary' %>

<% end %>

Rails/app/views/boards/edit.html.erb
<div class="d-flex align-items-center">
  <h1>編集</h1>
  <%= @board %>
  <div class="ml-auto boards__linkBox">
    <%# <a href="/boards" class="btn btn-outline-dark">掲示板一覧</a> %>
    <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark' %>
  </div>
</div>

<%= render partial: 'form', locals: { board: @board } %>

Rails/app/views/boards/index.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板一覧</h1>
  <div class="ml-auto boards__linkBox">

    <%= form_tag boards_path, method: :get, class: 'boards__searchForm' do %>
      <%= select_tag :tag_id,
          options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
          {
            prompt:   'タグで絞り込み',
            class:    'form-control boards__select',
            onchange: 'submit(this.form)'
          }
      %>
    <% end %>

    <%# <a class="btn btn-outline-dark" href="/boards/new">新規作成</a> %>
    <%= link_to '新規作成', new_board_path, class: 'btn btn-outline-dark' %>
  </div>
</div>

<% if flash[:notice] %>
  <div class="alert alert-danger"><%= flash[:notice] %></div>
<% end %>

<table class="table table-hover boards__table">
  <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>作成者</th>
      <th>作成日時</th>
      <th>更新日時</th>
      <th>詳細</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.id %></td>
        <td><%= board.title %></td>
        <td><%= board.name %></td>
        <td><%= board.created_at.strftime('%Y年 %m月 %d日 %H時 %M分') %></td>
        <td><%= board.updated_at.to_s(:datetime_jp) %></td>
        <td><%= link_to '詳細', board, class: 'btn btn-outline-dark' %></td>
        <td><%= link_to '削除', board, class: 'btn btn-outline-dark', method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @boards %>

Rails/app/views/boards/new.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板作成</h1>
  <div class="ml-auto boards__linkBox">
    <%# <a href="/boards" class="btn btn-outline-dark">掲示板一覧</a> %>
    <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark' %>
  </div>
</div>

<%= render partial: 'form', locals: { board: @board } %>

Rails/app/views/boards/show.html.erb
<div class="d-flex align-items-center mt-4 mb-4">
  <div class="ml-auto boards__linkBox">
    <%# <a href="/boards" class="btn btn-outline-dark">一覧</a> %>
    <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark' %>
    <%= link_to '編集', edit_board_path, class: 'btn btn-outline-dark' %>
    <%# <a href="/boards" class="btn btn-outline-dark">編集</a> %>
  </div>
</div>

<% if flash[:notice]%>
  <div class="alert alert-primary"><%= flash[:notice] %></div>
<% end %>

<%= render @board %>

<div class="p-comment__list">
  <div class="p-comment_listTitle">コメント</div>
  <%# @boardについているcommentsの分だけ、自動で回してくれる(_comment) %>
  <%= render @board.comments %> 
</div>

<%# <%= render partial: 'board', object: @board %>
<%# <%= render partial: 'comment_form', locals: { comment: @comment } %>
<%# 別ディレクトリのパーシャル使用 %>
<%= render partial: 'comments/form', locals: { comment: @comment } %>

<%# これでもOK %>
<%# <%= render @board %>

Rails/app/views/comments/_comment.html.erb
<div class="p-comment__item">
  <p><%= simple_format(comment.comment) %></p>
  <div class="p-comment__bottomLine">
    <span><%= comment.name %></span>
    <span><%= comment.created_at.to_s(:datetime_jp) %></span>
    <span><%= link_to '編集', edit_comment_path(id: comment.id)  %></span>
    <span><%= link_to '削除', comment, method: :delete, data: { confirm: '削除してもよろしいですか？' } %>
  </div>
</div>

Rails/app/views/comments/_form.html.erb
<%= render 'shared/error_messages' %>

<div class="p-comment__formBox">
  <p class="p-comment__formTitle">コメント記入</p>
  <%= form_for comment do |f| %>
    <%# コメント対象の掲示板IDを渡す %>
    <%= f.hidden_field :board_id %>
    <div class="form-group">
      <%= f.label :name, '名前' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :comment, 'コメント' %>
      <%= f.text_area :comment, class: 'form-control', rows: 4 %>
    </div>
    <%= f.submit '送信', class: 'btn btn-primary' %>
  <% end %>
</div>

Rails/app/views/comments/edit.html.erb
<% if flash[:error_messages] %>
  <div class="alert alert-danger">
    <ul>
      <% flash[:error_messages].each do |msg|%>
        <li><%= msg %>  </li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if flash[:comment] %>
  <div><span><%= flash[:comment] %></span></div>
  <hr>
  <div><span><%= flash[:flash_name] %></span></div>
  <hr>
  <div><span><%= flash[:flash_param] %></span></div>
  <hr>
<% end %>

<% if session[:test_session] %>
<hr>
sessionの値 : <span><%= session[:test_session] %></span>
<% end %>

<% if cookies[:test_cookie] %>
<hr>
cookieの値 : <span><%= cookies[:test_cookie] %></span>
<% end %>

<hr>


<%= form_for(@comment) do |f| %>
  <div class="form-group">
    <%= f.label :title, '名前' %>
    <%= f.text_field :name, class: 'form-control' %>
  <div>

  <div class="form-group">
    <%= f.label :title, 'コメント内容' %>
    <%= f.text_field :comment, class: 'form-control' %>
  </div>

  <%= f.submit '編集を終える', class: 'btn btn-primary' %>

<% end %>


<%= @comment %>
<%= @test %>

Rails/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

Rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

Rails/app/views/shared/_error_messages.html.erb
<% if flash[:error_messages] %>
  <div class="alert alert-danger">
    <ul>
      <% flash[:error_messages].each do |msg|%>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

Rails/app/views/users/me.html.erb
<h1>Users#me</h1>
<p>Find me in app/views/users/me.html.erb</p>

Rails/app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>